//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Node Package for Dynamo")]
[assembly: System.Reflection.AssemblyProduct("DynamoSample")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(c) 2014")]
[assembly: System.Reflection.AssemblyFileVersion("212.0.0.8414")]
[assembly: System.Reflection.AssemblyVersion("212.0.0.8414")]
[assembly: System.Reflection.AssemblyTitle("DynamoSample Core Nodes")]


